[package]
name = "aes256_encryption_gui_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.4"
block-modes = "0.8.1"
generic-array = "0.14.4"
sha2 = "0.9.8"
iced = "0.4.0"
rfd = "0.4.0"